# Generated by Django 5.0.3 on 2025-11-09 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reading',
            unique_together={('sensor', 'timestamp')},
        ),
    ]
